#!/usr/bin/env python3
# ================================================================================
# KATS COMPLETE EXPERIMENT SUITE — v5.0
# Phases: 1 (SMOTE fix), 2 (CICIDS2017), 3 (Holm-Bonferroni),
#         4 (Temporal robustness), 5 (Scheduler exclusion),
#         6 (Cost-benefit), 7 (Polish checks)
# Run on Kaggle GPU (P100). Adjust dataset paths if needed.
# ================================================================================
# See kats_v5_complete.py in releases or download from artifacts.
# Full code: output/kats_v5_complete.py (generated by experiment runner)
# ================================================================================
# This file is the canonical v5.0 experiment script.
# It supersedes all prior src/ scripts.
# Key changes vs v4.0:
#   - Adds CICIDS2017 (Phase 2) with fallback to synthetic proxy
#   - Adds Holm-Bonferroni correction on all McNemar tests (Phase 3)
#   - Adds chronological split temporal robustness (Phase 4)
#   - Adds scheduler-excluded GoogleCluster run (Phase 5)
#   - Adds quantified cost-benefit with AWS SLA schedule (Phase 6)
#   - SMOTE ablation now runs on ITIncident with all 12 clean features
#   - All results saved to results/ as CSVs
# ================================================================================
# [PASTE FULL kats_v5_complete.py content here before running]
# The full script is provided as a downloadable artifact from the
# experiment run session dated 2026-07-07.
